spring.application.name=scheduler
spring.datasource.url=jdbc:postgresql://${DS_URL}:${DS_PORT}/${DS_DB}
spring.datasource.username=${DS_USER}
spring.datasource.password=${DS_PWD}
spring.profiles.active=${ACTIVE_PROFILE}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MAIL PROPERTIES
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3ff050c1b63f33
spring.mail.password=c4821b6bc66912
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SCHEDULE

scheduler.agendamento.fixed-delay-ms=5000